name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport
    
    - run: ./gradlew lint   
    - uses: yutailang0119/action-android-lint@v1.0.2
      with:
          xml_path: build/reports/lint-results.xml
      
    - name: Build the app
      run: ./gradlew build
      
   
 
      
